"""rename_documentos_to_documento

Revision ID: 0bb9c49aaadc
Revises: 001_initial_migration
Create Date: 2025-01-02 00:36:36.420225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb9c49aaadc'
down_revision: Union[str, None] = '001_initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('documento', sa.String(length=20), nullable=False))
    op.drop_index('ix_clientes_documentos', table_name='clientes')
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=True)
    op.drop_column('clientes', 'documentos')
    op.create_index(op.f('ix_movimientos_vigencias_id_movimiento'), 'movimientos_vigencias', ['id_movimiento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_vigencias_id_movimiento'), table_name='movimientos_vigencias')
    op.add_column('clientes', sa.Column('documentos', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.create_index('ix_clientes_documentos', 'clientes', ['documentos'], unique=True)
    op.drop_column('clientes', 'documento')
    # ### end Alembic commands ###
