"""rename_mail_to_email

Revision ID: 5f9d895f0709
Revises: 0bb9c49aaadc
Create Date: 2025-01-02 00:50:17.838794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9d895f0709'
down_revision: Union[str, None] = '0bb9c49aaadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('email', sa.String(length=50), nullable=False))
    op.drop_index('ix_clientes_mail', table_name='clientes')
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.drop_column('clientes', 'mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('mail', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.create_index('ix_clientes_mail', 'clientes', ['mail'], unique=True)
    op.drop_column('clientes', 'email')
    # ### end Alembic commands ###
